apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: xppbi3nq5-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/xppbi3nq5-java-springboot-gitops